<?php
/**
 * Created by PhpStorm.
 * User: moment
 * Date: 2018/6/14
 * Time: 上午10:57
 */

namespace api\controllers;

use api\modules\v1\models\user\Member;
use Codeception\Util\ReflectionHelper;
use Prophecy\Doubler\ClassPatch\ReflectionClassNewInstancePatch;
use Yii;
use common\tools\Upload;
use yii\base\Model;
use yii\helpers\VarDumper;
use yii\rest\ActiveController;
use yii\web\UploadedFile;
use yii\web\BadRequestHttpException;

class UploadController extends ApiController
{
    public $model;
    public $modelClass = 'api\modules\v1\models\user\Member';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model = new Upload();
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions);
    }

    public function actionAvatar()
    {
        $dirPath = Yii::getAlias("@api");
        $model = $this->model;
        $model->scenario = 'url';
        $model->_type_model = 'api\modules\v1\models\user\Member';
        $model->_type_id = Yii::$app->user->id;
        $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
        if ($url = $model->upload($dirPath)) {
            return $url;
        }
    }

    public function actionPhoto()
    {
        $dirPath = Yii::getAlias("@api");
        $model = $this->model;
        $model->scenario = 'more';
        $model->_type_model = 'api\modules\v1\models\user\Member';
        $model->_type_id = Yii::$app->user->id;
        $model->imageFiles = UploadedFile::getInstances($model, 'imageFiles');
        if ($url = $model->uploads($dirPath)) {
            // 文件上传成功
            return $url;
        }
    }
}