<?php

namespace backend\modules\system\controllers;

use backend\controllers\Controller;
use backend\modules\system\models\AdminLog;
use backend\tools\PageParam;
use Yii;

class LogController extends Controller
{

    private $log;
    protected $page;
    protected $modelClass = 'backend\modules\system\models\AdminLog';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->log = new AdminLog();
        $this->page = new PageParam();
    }


    public function actionIndex()
    {

        return $this->render('index');
    }


    public function actionLogData()
    {
        $param = Yii::$app->request->get();
        return $this->page->getPageParam($this->modelClass,$param);
    }

}

